imageUrl: https://github.com/adidas/js-linter-configs/blob/master/logo.png
keywords:
  - eslint
  - tslint
  - stylelint
  - linter
  - shareable-configs
  - configuration
  - ecmascript
  - typescript
  - javascript
  - babel
  - jsx
  - react
  - vue
  - bem
